# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hopfield_UI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1155, 838)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.QFileDialog = QtWidgets.QWidget(self.centralwidget)
        self.QFileDialog.setGeometry(QtCore.QRect(60, 470, 441, 111))
        self.QFileDialog.setObjectName("QFileDialog")
        self.openFileButton = QtWidgets.QPushButton(self.QFileDialog)
        self.openFileButton.setGeometry(QtCore.QRect(10, 40, 211, 28))
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(14)
        self.openFileButton.setFont(font)
        self.openFileButton.setObjectName("openFileButton")
        self.selectedFileURLTextEdit = QtWidgets.QTextEdit(self.QFileDialog)
        self.selectedFileURLTextEdit.setGeometry(QtCore.QRect(230, 10, 201, 91))
        self.selectedFileURLTextEdit.setObjectName("selectedFileURLTextEdit")
        self.QFileDialog_2 = QtWidgets.QWidget(self.centralwidget)
        self.QFileDialog_2.setGeometry(QtCore.QRect(60, 590, 441, 91))
        self.QFileDialog_2.setObjectName("QFileDialog_2")
        self.openFileButton_2 = QtWidgets.QPushButton(self.QFileDialog_2)
        self.openFileButton_2.setGeometry(QtCore.QRect(10, 30, 211, 28))
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(14)
        self.openFileButton_2.setFont(font)
        self.openFileButton_2.setObjectName("openFileButton_2")
        self.selectedFileURLTextEdit_2 = QtWidgets.QTextEdit(self.QFileDialog_2)
        self.selectedFileURLTextEdit_2.setGeometry(QtCore.QRect(230, 10, 201, 71))
        self.selectedFileURLTextEdit_2.setObjectName("selectedFileURLTextEdit_2")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(590, 630, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(14)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(860, 520, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(870, 710, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(14)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.DegreeDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.DegreeDoubleSpinBox.setGeometry(QtCore.QRect(900, 630, 61, 31))
        self.DegreeDoubleSpinBox.setObjectName("DegreeDoubleSpinBox")
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(900, 580, 61, 31))
        self.spinBox.setObjectName("spinBox")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(590, 580, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_range = QtWidgets.QLabel(self.centralwidget)
        self.label_range.setGeometry(QtCore.QRect(780, 580, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(14)
        self.label_range.setFont(font)
        self.label_range.setText("")
        self.label_range.setObjectName("label_range")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(810, 630, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.input_image = QtWidgets.QLabel(self.centralwidget)
        self.input_image.setGeometry(QtCore.QRect(20, 10, 531, 441))
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.input_image.setFont(font)
        self.input_image.setAlignment(QtCore.Qt.AlignCenter)
        self.input_image.setObjectName("input_image")
        self.output_image = QtWidgets.QLabel(self.centralwidget)
        self.output_image.setGeometry(QtCore.QRect(600, 10, 531, 441))
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(24)
        self.output_image.setFont(font)
        self.output_image.setObjectName("output_image")
        self.input_dim2 = QtWidgets.QSpinBox(self.centralwidget)
        self.input_dim2.setGeometry(QtCore.QRect(720, 520, 61, 31))
        self.input_dim2.setObjectName("input_dim2")
        self.input_dim1 = QtWidgets.QSpinBox(self.centralwidget)
        self.input_dim1.setGeometry(QtCore.QRect(720, 480, 61, 31))
        self.input_dim1.setObjectName("input_dim1")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(590, 480, 121, 20))
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(590, 530, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(150, 690, 341, 87))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 339, 85))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.textEdit = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.textEdit.setGeometry(QtCore.QRect(0, 0, 341, 87))
        self.textEdit.setObjectName("textEdit")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(70, 700, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(590, 670, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(14)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_3.setGeometry(QtCore.QRect(590, 710, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(14)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setObjectName("checkBox_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1155, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "109504512"))
        self.openFileButton.setText(_translate("MainWindow", "Open Training File"))
        self.openFileButton_2.setText(_translate("MainWindow", "Open Testing File"))
        self.checkBox.setText(_translate("MainWindow", "Noisy Generation"))
        self.pushButton.setText(_translate("MainWindow", "Train"))
        self.pushButton_2.setText(_translate("MainWindow", "Test"))
        self.label.setText(_translate("MainWindow", "Choose entry from"))
        self.label_2.setText(_translate("MainWindow", "Degree"))
        self.input_image.setText(_translate("MainWindow", "Input image will appear here"))
        self.output_image.setText(_translate("MainWindow", "Output image will appear here"))
        self.label_3.setText(_translate("MainWindow", "Input Dim1"))
        self.label_4.setText(_translate("MainWindow", "Input Dim2"))
        self.label_5.setText(_translate("MainWindow", "Energy \n"
"History"))
        self.checkBox_2.setText(_translate("MainWindow", "Use Threshold"))
        self.checkBox_3.setText(_translate("MainWindow", "Async Mode"))

